name: Bundling for Various Platforms

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  macos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # You may pin to the exact commit or the version.
      # uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d
      - name: The Determinate Nix Installer
        uses: DeterminateSystems/nix-installer-action@v16
      # You may pin to the exact commit or the version.
      # uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b
      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Bundle for Intel
        run: nix bundle .#target.x86_64-macos-none
      - name: Bundle for Arm
        run: nix bundle .#target.aarch64-macos-none

  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # You may pin to the exact commit or the version.
      # uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d
      - name: The Determinate Nix Installer
        uses: DeterminateSystems/nix-installer-action@v16
      # You may pin to the exact commit or the version.
      # uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b
      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Bundle with GNU
        run: nix bundle .#target.x86_64-linux-gnu
      - name: Bundle with MUSL
        run: nix bundle .#target.x86_64-linux-musl

  windows:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # You may pin to the exact commit or the version.
      # uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d
      - name: The Determinate Nix Installer
        uses: DeterminateSystems/nix-installer-action@v16
      # You may pin to the exact commit or the version.
      # uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b
      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Bundle with GNU
        run: nix bundle .#target.x86_64-windows-gnu
      - name: Bundle with MSVC
        run: nix bundle .#target.x86_64-windows-msvc
